version: "3.7"

services:
  pysat:
    image: pysat
    ports:
      - "8880:8888"
    build: 
      context: .
      dockerfile: pysat.Dockerfile
  pysat-kamodo:
    image: pysat_kamodo
    ports:
      - "8881:8888"
    build:
      context: .
      dockerfile: dockerfiles/pysatKamodo.Dockerfile
    volumes:
      - type: bind
        source: ${PWD}
        target: /pysatKamodo
  pysat-madrigal:
    image: pysat_madrigal
    ports:
      - "8882:8888"
    build:
      context: .
      dockerfile: dockerfiles/pysatMadrigal.Dockerfile
    volumes:
      - type: bind
        source: ${PWD}
        target: /pysatKamodo
